language: go

go:
- 1.12.x

go_import_path: github.com/nektro/andesite

before_deploy:
- git config --local user.name "Meghan Denny"
- git config --local user.email "${GIT_EMAIL}"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y.%m.%d')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- go get -u -v .
- ./scripts/build_all.sh

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: dist/*
  skip_cleanup: true
