language: go

go:
- 1.12.x

go_import_path: github.com/nektro/andesite

before_deploy:
- git config --local user.name "YOUR GIT USER NAME"
- git config --local user.email "YOUR GIT USER EMAIL"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y.%m.%d')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH

deploy:
  provider: releases
  script:
    - make packages
    - make travis
  api_key: "${GH_TOKEN}"
  file: dist/*
  skip_cleanup: true
