# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nektro/nektro
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: ./scripts/build_all.sh
      - run: go get github.com/tcnksm/ghr
      - run: VERSION=$(date +'%Y.%m.%d')-$(git log --format=%h -1)
      # - run: ~/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./bin/

      - store_artifacts:
          path: ./bin/
